name: CI - Test Next.js App

on:
  pull_request:
    branches: 
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    working-directory: ./housekeeping_daniel_wouter

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "^18"

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test:ci
